### PR TITLE
Add ArvanCloud Provider

### PR DESCRIPTION
**Pull request by hatamiarash7**
Add ArvanCloud provider for DNS. This provider also has other services like VPS and PaaS which I will add in the next PRs.

### CODE REVIEW

**Review by ehsandeep — COMMENTED** [review]
@hatamiarash7, thank you for adding the new provider.

Could you please include a redacted version of the CLI output and the JSON format?

**Comment by hatamiarash7** [comment]
Of course

telegram-cloud-document-4-5967648528539849314

telegram-cloud-document-4-5967648528539849315

**Comment by ehsandeep** [comment]
@hatamiarash7, can we append the domain name to the `dns_name` value so that the output contains a usable DNS name for further use? For example, `grafana` would become `grafana.xyz.com`

**Comment by hatamiarash7** [comment]
I got the initial idea about the structure of your project from Cloudflare. There was no such output there, and by the way, I wondered how to make useful use of these records.

I have now fixed this problem in this PR. I will open a separate PR for Cloudflare as well.

**Comment by hatamiarash7** [comment]
Any update?

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
