### PR TITLE
Add Openstack support

### PR DESCRIPTION
**Pull request by S0obi**
# Description

Add support for Openstack API by creating a new `openstack` provider.

This first implementation supports username/password authentication with a tenant name. It will display all floating ips defined for all Openstack Instances.

See https://github.com/projectdiscovery/cloudlist/issues/258

### CODE REVIEW

**Review by tarunKoyalwar — CHANGES_REQUESTED** [review]
@S0obi , resolve merge conflicts and
```sh
go mod tidy
```

**Comment by S0obi** [comment]
> @S0obi , resolve merge conflicts and
> 
> ```shell
> go mod tidy
> ```

Hey @tarunKoyalwar, I rebased on dev and executed go mod tidy

**Comment by tarunKoyalwar** [comment]
Thanks @S0obi , I will approve this once tests are successful

**Comment by S0obi** [comment]
@tarunKoyalwar I justed added missing documentation for `tenant_name` parameter. Sorry for that :)

**Comment by tarunKoyalwar** [comment]
@S0obi  , no worries

**Review by tarunKoyalwar — APPROVED** [review]
lgtm!

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
